apiVersion: hazelcast.com/v1alpha1
kind: HazelcastEnterprise
metadata:
  name: my-cluster
  namespace: syrius-hazelcast
spec:
  cluster:
    memberCount: 3

  mancenter:
    # ingress configuration for mancenter
    ingress:
      enabled: true
    persistence:
      size: 1Gi

  hazelcast:
    licenseKeySecretName: hz-license-key-secret

    hot-restart-persistence:
      enabled: ${hazelcast.hotRestart}
      base-dir: /data/hot-restart
      validation-timeout-seconds: 1200
      data-load-timeout-seconds: 900
      auto-remove-stale-data: true
    management-center:
      enabled: ${hazelcast.mancenter.enabled}
      url: ${hazelcast.mancenter.url}

    yaml:
      hazelcast:
        serialization:
          allow-override-default-serializers: true
        client:
          statistics:
            enabled: true
        enabled: true
        cluster-name: my-cluster
        native-memory:
          enabled: true
          allocator-type: STANDARD
          size:
            unit: GIGABYTES
            value: 2
          min-block-size: 128
          page-size: 123
          metadata-space-percentage: 12.5
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
              service-name: ${serviceName}
              namespace: ${namespace}
              resolve-not-ready-addresses: true
        map:
          persons:
            in-memory-format: NATIVE
            cache-deserialized-values: INDEX-ONLY
            backup-count: 1
            async-backup-count: 2
            read-backup-data: true
            eviction:
              eviction-policy: LRU
              max-size-policy: PER_NODE
              size: 9000
          orders:
            in-memory-format: NATIVE
            cache-deserialized-values: INDEX-ONLY
            eviction:
              eviction-policy: LRU
              max-size-policy: PER_NODE
              size: 9000
  securityContext:
    enabled: true
    runAsUser: '1000760000'
    fsGroup: '1000760000'
