apiVersion: hazelcast.com/v1alpha1
kind: HazelcastEnterprise
metadata:
  name: hz
  namespace: syrius-hazelcast
spec:
  cluster:
    memberCount: 3

  mancenter:
    # ingress configuration for mancenter
    ingress:
      enabled: true
    persistence:
      size: 1Gi
  hazelcast:
    licenseKeySecretName: hz-license-key-secret
  yaml:
    hazelcast:
      cluster-name: my-cluster
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: ${serviceName}
            namespace: ${namespace}
            resolve-not-ready-addresses: true
        ssl:
          enabled: ${hazelcast.ssl}
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
        hot-restart-persistence:
          enabled: ${hazelcast.hotRestart}
          base-dir: /data/hot-restart
          validation-timeout-seconds: 1200
          data-load-timeout-seconds: 900
          auto-remove-stale-data: true
        management-center:
          enabled: ${hazelcast.mancenter.enabled}
          url: ${hazelcast.mancenter.url}
      map:
        persons:
          in-memory-format: BINARY
          cache-deserialized-values: INDEX-ONLY
          backup-count: 0
          async-backup-count: 2
          read-backup-data: true
          eviction:
            eviction-policy: LRU
            max-size-policy: PER_NODE
            size: 9000
        orders:
          in-memory-format: BINARY
          cache-deserialized-values: INDEX-ONLY
          eviction:
            eviction-policy: LRU
            max-size-policy: PER_NODE
            size: 9000
  securityContext:
    runAsUser: '1000760000'
    fsGroup: '1000760000'
