app:
  name: cachetest-main
spring:
  cache:
    type: hazelcast
    file: config/kube-hazelcast.xml
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgresdb
    username: postgresadmin
    password: mysecretPassword$



