app:
  name: cachetest-main
spring:
  profiles:
    active: ${APP:dev}
  main:
    banner-mode: off
  jmx:
    enabled: false
  jsp-servlet:
    registered: false
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  mobile:
    sitepreference:
      enabled: false
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  cache:
    type: redis
    timeout: 60
    cacheExpirations:
      persons: 1800



