kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-5432-1
spec:
  podSelector:
    matchLabels:
      app: postgresql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: app
      ports:
        - protocol: TCP
          port: 5432
